Tisseo\EndivBundle\Entity\Alias:
    type: entity
    table: alias
    indexes:
        IDX_E16C6B941AD056BA:
            columns:
                - stop_area_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        stopArea:
            targetEntity: StopArea
            cascade: {  }
            mappedBy: null
            inversedBy: alias
            joinColumns:
                stop_area_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
