Tisseo\EndivBundle\Entity\Calendar:
    type: entity
    table: calendar
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        calendarType:
            type: calendar_type
            requireSQLConversion: true
            comment: ''
            column: calendar_type
    manyToOne:
        lineVersion:
            targetEntity: LineVersion
            mappedBy: null
            inversedBy: null
            joinColumns:
                line_version_id:
                    referencedColumnName: id
    oneToMany:
        periodTrips:
            targetEntity: Trip
            mappedBy: periodCalendar
            inversedBy: null
            orphanRemoval: false
            fetch: 'EXTRA_LAZY'
        dayTrips:
            targetEntity: Trip
            mappedBy: dayCalendar
            inversedBy: null
            orphanRemoval: false
            fetch: 'EXTRA_LAZY'
        calendarDatasources:
            targetEntity: CalendarDatasource
            cascade: ['persist', 'remove']
            mappedBy: calendar
            inversedBy: null
            orphanRemoval: true
            fetch: 'EXTRA_LAZY'
        accessibilityTypes:
            targetEntity: AccessibilityType
            mappedBy: calendar
            inversedBy: null
            orphanRemoval: true
            fetch: 'EXTRA_LAZY'
    lifecycleCallbacks: {  }
