Tisseo\EndivBundle\Entity\Depot:
    type: entity
    table: depot
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        shortName:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
            column: short_name
        longName:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
            column: long_name

    oneToMany:
        lineVersions:
            targetEntity: LineVersion
            mappedBy: depot
            inversedBy: null
            fetch: 'EXTRA_LAZY'
    lifecycleCallbacks: {  }
