Tisseo\EndivBundle\Entity\LineVersion:
    type: entity
    table: line_version
    indexes:
        IDX_AB852A4E217CF67:
            columns:
                - bg_color_id
        IDX_AB852A452CEBCE5:
            columns:
                - fg_color_id
        IDX_AB852A44D7B7542:
            columns:
                - line_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        version:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        startDate:
            type: date
            nullable: false
            comment: 'Date de debut d''offre.'
            column: start_date
        endDate:
            type: date
            nullable: true
            comment: 'Date effective de fin d''offre, non reneignee a la creation.'
            column: end_date
        plannedEndDate:
            type: date
            nullable: false
            comment: 'Date de fin previsionnelle d''offre.'
            column: planned_end_date
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        forwardDirection:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: forward_direction
        backwardDirection:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: backward_direction
        comment:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        depot:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        status:
            type: line_version_status
            requireSQLConversion: true
            comment: ''
    manyToOne:
        bgColor:
            targetEntity: Color
            mappedBy: null
            inversedBy: null
            joinColumns:
                bg_color_id:
                    referencedColumnName: id
            orphanRemoval: false
        fgColor:
            targetEntity: Color
            mappedBy: null
            inversedBy: null
            joinColumns:
                fg_color_id:
                    referencedColumnName: id
            orphanRemoval: false
        line:
            targetEntity: Line
            mappedBy: null
            inversedBy: lineVersions
            joinColumns:
                line_id:
                    referencedColumnName: id
        schematic:
            targetEntity: Schematic
            mappedBy: null
            inversedBy: null
            joinColumns:
                schematic_id:
                    referencedColumnName: id
    oneToMany:
        lineGroupContents:
            targetEntity: LineGroupContent
            cascade: ['persist', 'remove']
            mappedBy: lineVersion
            inversedBy: null
            orphanRemoval: true
            fetch: 'EXTRA_LAZY'
        gridCalendars:
            targetEntity: GridCalendar
            cascade: ['persist', 'remove']
            mappedBy: lineVersion
            inversedBy: null
            orphanRemoval: true
            fetch: 'EXTRA_LAZY'
        modifications:
            targetEntity: Modification
            cascade: ['persist', 'remove']
            mappedBy: lineVersion
            inversedBy: null
            orphanRemoval: true
        printings:
            targetEntity: Printing
            cascade: ['persist', 'remove']
            mappedBy: lineVersion
            inversedBy: null
            orphanRemoval: true
        routes:
            targetEntity: Route
            cascade: ['persist', 'remove']
            mappedBy: lineVersion
            inversedBy: null
            orphanRemoval: true
            fetch: 'EXTRA_LAZY'
    lifecycleCallbacks: {  }
