Tisseo\EndivBundle\Entity\LineGroupGis:
    type: entity
    table: line_group_gis
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            fixed: false
            comment: ''
        nbBus:
            column: nb_bus
            type: integer
            nullable: true
            fixed: false
            comment: ''
        comment:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    oneToMany:
        lineGroupGisContents:
            targetEntity: LineGroupGisContent
            cascade: ['persist', 'remove']
            mappedBy: lineGroupGis
            inversedBy: null
            orphanRemoval: true
    lifecycleCallbacks: {  }
