Tisseo\EndivBundle\Entity\Line:
    type: entity
    table: line
    indexes:
        IDX_D114B4F6635D2D67:
            columns:
                - physical_mode_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        number:
            type: string
            nullable: false
            length: 10
            fixed: false
            comment: 'Numéro de la ligne. Peut ne pas etre numerique. Par exple : T1, A ou L16 sont des numeros.'
        priority:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Priorité de la ligne. Sert notamment a trier les lignes dans les listes de lignes.'
    oneToMany:
        lineDatasources:
            targetEntity: LineDatasource
            cascade: ['persist', 'remove']
            mappedBy: line
            inversedBy: null
        lineVersions:
            targetEntity: LineVersion
            cascade: ['persist', 'remove']
            mappedBy: line
            inversedBy: null
        schematics:
            targetEntity: Schematic
            cascade: ['persist', 'remove']
            mappedBy: line
            inversedBy: null
        lineGroupGisContents:
            targetEntity: LineGroupGisContent
            cascade: ['persist', 'remove']
            mappedBy: line
            inversedBy: null
        lineStatuses:
            orderBy: { 'dateTime': 'DESC' }
            targetEntity: LineStatus
            cascade: ['persist', 'remove']
            mappedBy: line
            inversedBy: null
    manyToOne:
        physicalMode:
            targetEntity: PhysicalMode
            mappedBy: null
            inversedBy: null
            joinColumns:
                physical_mode_id:
                    referencedColumnName: id
    manyToMany:
        boards:
            targetEntity: Tisseo\EndivBundle\Entity\Ogive\Board
            cascade: ['persist', 'remove']
            joinTable:
                name: ogive.line_board
                joinColumns:
                    -
                        name: line_id
                        referencesColumn: id
                inverseJoinColumns:
                    -
                        name: board_id
                        referencedColumnName: id
    lifecycleCallbacks: {  }
