Tisseo\EndivBundle\Entity\LineGroupGis:
    type: entity
    table: line_group_gis
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            fixed: false
        nbBus:
            column: nb_bus
            type: integer
            nullable: true
            fixed: false
        comment:
            type: text
            nullable: true
            length: null
            fixed: false
    oneToMany:
        printings:
            targetEntity: Tisseo\EndivBundle\Entity\PrintingLineGroupGis
            cascade: ['persist', 'remove']
            mappedBy: lineGroupGis
            orphanRemoval: true
    manyToMany:
        lines:
            targetEntity: Tisseo\EndivBundle\Entity\Line
            mappedBy: lineGroupGis
    lifecycleCallbacks: {  }
