Tisseo\EndivBundle\Entity\LineGroupContent:
    type: entity
    table: line_group_content
    indexes:
        IDX_E02E70CCF50734EE:
            columns:
                - line_version_id
        IDX_E02E70CC2D37893D:
            columns:
                - line_group_id
    id:
        lineGroup:
            associationKey: true
        lineVersion:
            associationKey: true
    fields:
        parent:
            type: boolean
            nullable: true
            comment: ''
            column: is_parent
    manyToOne:
        lineVersion:
            targetEntity: LineVersion
            cascade: { }
            mappedBy: null
            inversedBy: lineGroupContents
            joinColumns:
                line_version_id:
                    referencedColumnName: id
        lineGroup:
            targetEntity: LineGroup
            cascade: ['persist', 'remove']
            mappedBy: null
            inversedBy: lineGroupContents
            joinColumns:
                line_group_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
