Tisseo\EndivBundle\Entity\ModificationLink:
    type: entity
    table: modification_link
    indexes:
        modification_link_line_version_id_idx:
            columns:
                - line_version_id
        modification_link_modification_id_idx:
            columns:
                - modification_id
        modification_link_resolved_idx:
            columns:
                - resolved_in
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        date:
            type: date
            nullable: false
            comment: 'Date de la prise d effet de la modification.'
    manyToOne:
        modification:
            targetEntity: Modification
            mappedBy: null
            inversedBy: modificationLinks
            joinColumns:
                modification_id:
                    referencedColumnName: id
        resolvedIn:
            targetEntity: Modification
            mappedBy: null
            inversedBy: null
            joinColumns:
                resolved_in:
                    referencedColumnName: id
        lineVersion:
            targetEntity: LineVersion
            mappedBy: null
            inversedBy: modificationLinks
            joinColumns:
                line_version_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
