Tisseo\EndivBundle\Entity\OdtArea:
    type: entity
    table: odt_area
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
    fields:
        name:
            type: string
            nullable: false
            length: 30
            fixed: false
            comment: ''
        comment:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    oneToOne:
        waypoint:
            targetEntity: Waypoint
            cascade: { }
            mappedBy: odtArea
    oneToMany:
        odtStops:
            targetEntity: OdtStop
            cascade: ['persist', 'remove']
            mappedBy: odtArea
            inversedBy: null
            orphanRemoval: true
            fetch: 'EXTRA_LAZY'
    lifecycleCallbacks: {  }
