Tisseo\EndivBundle\Entity\Ogive\Channel:
    type: entity
    table: ogive.channel
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
        maxSize:
            type: integer
            nullable: true
            column: max_size
    lifecycleCallbacks: {  }
