Tisseo\EndivBundle\Entity\Ogive\EventStepText:
    type: entity
    table: ogive.event_step_text
    indexes:
        IDX_460E6A36F6E5B733:
            columns:
                - event_step_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        label:
            type: string
            nullable: false
            length: 40
            fixed: false
            comment: ''
        type:
            type: integer
            nullable: false
            default: 0
            column: text_type
        text:
            type: string
            nullable: false
            fixed: false
            comment: ''
    manyToOne:
        eventStep:
            targetEntity: EventStep
            inversedBy: texts
            joinColumns:
                event_step_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
