Tisseo\EndivBundle\Entity\Ogive\LineStop:
    type: entity
    table: ogive.line_stop
    repositoryClass: Tisseo\EndivBundle\Entity\Ogive\LineStopRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        stopId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: stop_id
        lineId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: line_id
        directionName:
            type: string
            nullable: false
            length: 80
            fixed: false
            comment: ''
            column: direction_name
    lifecycleCallbacks: {  }
