Tisseo\EndivBundle\Entity\Ogive\OgiveObject:
    type: entity
    table: ogive.object
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        type:
            type: text
            nullable: false
            column: object_type
        ref:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 'Référence de l''objet dans le référentiel lié au type (si ligne, alors TID, si mécanisme, alors PIVERT...)'
            column: object_ref
    oneToMany:
        messages:
            targetEntity: Message
            mappedBy: object
            orderBy: {'startDatetime': 'asc'}
    manyToMany:
        groupObject:
            targetEntity: GroupObject
            inversedBy: objects
            joinTable:
                name: ogive.group_object_content
                joinColumns:
                    -
                        name: object_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: group_object_id
                        referencedColumnName: id
    lifecycleCallbacks: {  }
