Tisseo\EndivBundle\Entity\Ogive\Message:
    type: entity
    table: ogive.message
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        title:
            type: string
            nullable: false
            length: 60
            fixed: false
        subtitle:
            type: string
            nullable: false
            length: 255
            fixed: false
        content:
            type: text
            nullable: false
            length: null
            fixed: false
            column: content
        startDatetime:
            type: datetime
            nullable: true
            column: start_datetime
        endDatetime:
            type: datetime
            nullable: true
            column: end_datetime
        modificationDatetime:
            type: datetime
            nullable: false
            column: modification_datetime
            gedmo:
                timestampable:
                    on: update
        prehome:
            type: boolean
            nullable: false
            column: is_prehome
        push:
            type: boolean
            nullable: false
            column: is_push
    oneToMany:
        files:
            targetEntity: MessageFile
            mappedBy: message
            cascade: ['persist', 'remove']
    manyToOne:
        event:
            targetEntity: Event
            inversedBy: messages
            joinColumns:
                event_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
