Tisseo\EndivBundle\Entity\Ogive\Scenario:
    type: entity
    table: ogive.scenario
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        severityId:
            type: guid
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: chaos_severity
        causeId:
            type: guid
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: chaos_cause
    oneToMany:
        scenarioSteps:
            targetEntity: ScenarioStep
            cascade: [remove]
            inversedBy: null
            mappedBy: scenario
            orderBy: {'name': 'asc'}
    lifecycleCallbacks: {  }
