Tisseo\EndivBundle\Entity\Ogive\ScenarioStepText:
    type: entity
    table: ogive.scenario_step_text
    indexes:
        scenario_step_text_pkey:
            columns:
                - scenario_step_id
                - text_id
    id:
        scenarioStep:
            associationKey: true
        text:
            associationKey: true
    fields:
        type:
            type: integer
            nullable: false
            default: 0
            column: text_type
        rank:
            type: integer
            nullable: false
    manyToOne:
        scenarioStep:
            targetEntity: ScenarioStep
            inversedBy: scenarioStepTexts
            joinColumns:
                scenario_step_id:
                    referencedColumnName: id
        text:
            targetEntity: Text
            joinColumns:
                text_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
