Tisseo\EndivBundle\Entity\Ogive\Message:
    type: entity
    table: ogive.message
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        title:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
        subtitle:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        content:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: content
        urlPj:
            type: string
            column: url_pj
        startDatetime:
            type: datetime
            nullable: true
            comment: ''
            column: start_datetime
        endDatetime:
            type: datetime
            nullable: true
            comment: ''
            column: end_datetime
    manyToMany:
        channels:
            targetEntity: Channel
            joinTable:
                name: ogive.channel_message
                joinColumns:
                    -
                        name: message_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: channel_id
                        referencedColumnName: id
    lifecycleCallbacks: {  }
