Tisseo\EndivBundle\Entity\Ogive\ScenarioStep:
    type: entity
    table: ogive.scenario_step
    indexes:
        IDX_311CB635D080F7BD:
            columns:
                - scenario_step_parent_id
        IDX_311CB635E04E49DF:
            columns:
                - scenario_id
        IDX_311CB6354D085745:
            columns:
                - connector_id
        IDX_311CB6352CA2FD66:
            columns:
                - connector_param_list_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        rank:
            type: integer
            nullable: true
            unsigned: false
            comment: 'Rang de l''étape. Les rangs sont simplement ordonnés ; ils ne se suivent pas forcément.'
            column: rank
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        moment:
            type: integer
            nullable: false
            column: moment
    manyToOne:
        scenarioStepParent:
            targetEntity: ScenarioStep
            inversedBy: scenarioSteps
            joinColumns:
                scenario_step_parent_id:
                    referencedColumnName: id
        scenario:
            targetEntity: Scenario
            inversedBy: scenarioSteps
            joinColumns:
                scenario_id:
                    referencedColumnName: id
        connector:
            targetEntity: Connector
            inversedBy: scenarioSteps
            joinColumns:
                connector_id:
                    referencedColumnName: id
        connectorParamList:
            targetEntity: ConnectorParamList
            inversedBy: scenarioSteps
            joinColumns:
                connector_param_list_id:
                    referencedColumnName: id
    oneToMany:
        scenarioStepTexts:
            targetEntity: ScenarioStepText
            mappedBy: scenarioStep
            cascade: ['persist', 'remove']
            orderBy: {'rank': 'asc'}
        scenarioSteps:
            targetEntity: ScenarioStep
            mappedBy: scenarioStepParent
            cascade: ['remove']
            orderBy: {'name': 'asc'}
    lifecycleCallbacks: {  }
