Tisseo\EndivBundle\Entity\Ogive\LineBoard:
    type: entity
    table: ogive.line_board
    indexes:
        IDX_9AF6E35AE7EC5785:
            columns:
                - board_id
    id:
        lineId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: line_id
    oneToOne:
        board:
            targetEntity: Board
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                board_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
