Tisseo\EndivBundle\Entity\Ogive\ConnectorParam:
    type: entity
    table: ogive.connector_param
    indexes:
        IDX_850945B42CA2FD66:
            columns:
                - connector_param_list_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        type:
            type: integer
            nullable: false
            column: param_type
        param:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        connectorParamList:
            targetEntity: ConnectorParamList
            cascade: {  }
            mappedBy: null
            inversedBy: connectorParams
            joinColumns:
                connector_param_list_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
