Tisseo\EndivBundle\Entity\Ogive\Period:
    type: entity
    table: ogive.period
    indexes:
        IDX_8544703B71F7E88B:
            columns:
                - event_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        startDate:
            type: datetime
            nullable: false
            column: start_date
        endDate:
            type: datetime
            nullable: false
            column: end_date
    manyToOne:
        event:
            targetEntity: Event
            inversedBy: periods
            joinColumns:
                event_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
