Tisseo\EndivBundle\Entity\Ogive\Event:
    type: entity
    table: ogive.event
    indexes:
        IDX_18CB994DF4EFF44D:
            columns:
                - event_parent_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        chaosSeverity:
            type: guid
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: chaos_severity
        chaosInternalCause:
            type: string
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: chaos_internal_cause
        isPublished:
            type: boolean
            nullable: true
            column: is_published
        status:
            type: integer
            nullable: false
            column: status
        chaosDisruptionId:
            type: guid
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: chaos_disruption_id
        reference:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: 'Nom externe de l''événement, issu de CHAOS : disruption.reference. Non unique.'
        isEmergency:
            type: boolean
            nullable: false
            comment: 'Est à true si l''événement est de type urgence. Structurant pour son apparition dans les listes.'
            default: false
            column: is_emergency
        login:
            type: text
            nullable: false
            length: 40
            fixed: false
    manyToOne:
        eventParent:
            targetEntity: Event
            mappedBy: null
            inversedBy: null
            joinColumns:
                event_parent_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        periods:
            targetEntity: Period
            mappedBy: event
            cascade: ['remove', 'persist']
            orderBy: {'startDate': 'asc'}
        eventSteps:
            targetEntity: EventStep
            mappedBy: event
            cascade: ['remove', 'persist']
            onDelete: 'cascade'
            orderBy: {'rank': 'asc'}
        eventDatasources:
            targetEntity: EventDatasource
            mappedBy: event
            cascade: ['remove', 'persist']
            orderBy: {'code': 'asc'}
        eventObjects:
            targetEntity: EventObject
            mappedBy: event
            cascade: ['remove', 'persist']
    lifecycleCallbacks: {  }
