Tisseo\EndivBundle\Entity\Ogive\Message:
    type: entity
    table: ogive.message
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        title:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
        subtitle:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        mailText:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: mail_text
        isForWebsite:
            type: boolean
            nullable: false
            comment: 'Est à true si l''enregistrement est à mettre à disposition des info réseau'
            default: false
            column: is_for_website
        isForPti:
            type: boolean
            nullable: false
            comment: 'Est à true si l''enregistrement est à mettre à disposition de l''IV personnalisée'
            default: false
            column: is_for_pti
        pushApps:
            type: boolean
            nullable: false
            default: false
            column: push_apps
        prehome:
            type: boolean
            nullable: false
            default: false
            column: prehome
        urlPj:
            type: string
            column: url_pj
        eventId:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: event_id
        startDatetime:
            type: datetime
            nullable: true
            comment: ''
            column: start_datetime
        endDatetime:
            type: datetime
            nullable: true
            comment: ''
            column: end_datetime
    lifecycleCallbacks: {  }
