Tisseo\EndivBundle\Entity\RouteExportDestination:
    type: entity
    table: route_export_destination
    indexes:
        IDX_D60ABFC6A574F401:
            columns:
                - export_destination_id
        IDX_D60ABFC634ECB4E6:
            columns:
                - route_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    manyToOne:
        exportDestination:
            targetEntity: ExportDestination
            cascade: {  }
            mappedBy: null
            inversedBy: routeExportDestinations
            joinColumns:
                export_destination_id:
                    referencedColumnName: id
            orphanRemoval: false
        route:
            targetEntity: Route
            cascade: {  }
            mappedBy: null
            inversedBy: routeExportDestinations
            joinColumns:
                route_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
