Tisseo\EndivBundle\Entity\Schematic:
    type: entity
    table: schematic
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        comment:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        date:
            type: datetime
            nullable: false
            comment: ''
        deprecated:
            type: boolean
            nullable: true
            comment: ''
        filePath:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: file_path
    manyToOne:
        line:
            targetEntity: Line
            mappedBy: null
            inversedBy: schematics
            joinColumns:
                line_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
    properties:
        file:
            - File:
                maxSize: 2048k
