Tisseo\EndivBundle\Entity\Schematic:
    type: entity
    table: schematic
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
        comment:
            type: string
            nullable: false
            length: 255
            fixed: false
        date:
            type: datetime
            nullable: false
        deprecated:
            type: boolean
            nullable: true
        groupGis:
            type: boolean
            nullable: false
            column: group_gis
        file:
            type: text
            nullable: true
            length: null
            fixed: false
            column: file_path
    manyToOne:
        line:
            targetEntity: Line
            inversedBy: schematics
            joinColumns:
                line_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        lineVersions:
            targetEntity: LineVersion
            cascade: ['persist']
            mappedBy: schematic
            fetch: 'EXTRA_LAZY'
    properties:
        file:
            - File:
                maxSize: 2048k
