Tisseo\EndivBundle\Entity\Stop:
    type: entity
    table: stop
    indexes:
        IDX_B95616B6E525EB55:
            columns:
                - master_stop_id
        IDX_B95616B61AD056BA:
            columns:
                - stop_area_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
    oneToOne:
        waypoint:
            targetEntity: Waypoint
            cascade: {  }
            mappedBy: stop
    oneToMany:
        stopDatasources:
            orderby: { 'startDate': 'ASC' }
            targetEntity: StopDatasource
            cascade: ['persist', 'remove']
            mappedBy: stop
            inversedBy: null
            fetch: 'EXTRA_LAZY'
        stopHistories:
            targetEntity: StopHistory
            cascade: ['persist', 'remove']
            mappedBy: stop
            inversedBy: null
            fetch: 'EXTRA_LAZY'
        stopAccessibilities:
            targetEntity: StopAccessibility
            cascade: ['persist', 'remove']
            mappedBy: stop
            inversedBy: null
            fetch: 'EXTRA_LAZY'
        phantoms:
            targetEntity: Stop
            cascade: []
            mappedBy: masterStop
            inversedBy: null
            fetch: 'EXTRA_LAZY'
        odtStops:
            targetEntity: OdtStop
            cascade: ['persist', 'remove']
            mappedBy: stop
            inversedBy: null
            fetch: 'EXTRA_LAZY'
    manyToOne:
        masterStop:
            targetEntity: Stop
            cascade: {  }
            mappedBy: null
            inversedBy: phantoms
            joinColumns:
                master_stop_id:
                    referencedColumnName: id
            orphanRemoval: false
        stopArea:
            targetEntity: StopArea
            cascade: {  }
            mappedBy: null
            inversedBy: stops
            joinColumns:
                stop_area_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
