Tisseo\EndivBundle\Entity\Waypoint:
    type: entity
    table: waypoint
    indexes:
        waypoint_id_idx:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    oneToOne:
        stop:
            targetEntity: Stop
            mappedBy: null
            inversedBy: null
            joinColumns:
                id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
