Tisseo\EndivBundle\Entity\Waypoint:
    type: entity
    table: waypoint
    indexes:
        waypoint_id_idx:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
#    oneToOne:
#        stop:
#            targetEntity: Stop
#            mappedBy: null
#            inversedBy: null
#            joinColumns:
#                id:
#                    referencedColumnName: id
    oneToOne:
        area:
            targetEntity: OdtArea
            inversedBy: waypoint
            joinColumn:
                name: id
                referencedColumnName: id
        stop:
            targetEntity: Stop
            inversedBy: waypoint
            joinColumn:
                name: id
                referencedColumnName: id
    lifecycleCallbacks: {  }
