services:
    tisseo_endiv.ogive.manager.ogive:
        abstract: true
        class: 'Tisseo\EndivBundle\Services\Ogive\OgiveManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']
    tisseo_endiv.ogive.manager.scenario_step:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\ScenarioStepManager'
        calls:
            - [setSerializer, ['@jms_serializer']]
    tisseo_endiv.ogive.manager.scenario:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\ScenarioManager'
        calls:
            - [setSerializer, ['@jms_serializer']]
    tisseo_endiv.ogive.manager.connector_param_list:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\ConnectorParamListManager'
        calls:
            - [setSerializer, ['@jms_serializer']]
    tisseo_endiv.ogive.manager.connector:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\ConnectorManager'
    tisseo_endiv.ogive.manager.text:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\TextManager'
        calls:
            - [setSerializer, ['@jms_serializer']]
    tisseo_endiv.ogive.manager.event:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\EventManager'
    tisseo_endiv.ogive.manager.event_step:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\EventStepManager'
    tisseo_endiv.ogive.manager.event_step_text:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\EventStepTextManager'
    tisseo_endiv.ogive.manager.event_step_status:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\LinkEventStepStatusManager'
    tisseo_endiv.ogive.manager.period:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\PeriodManager'
    tisseo_endiv.ogive.manager.event_object:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\EventObjectManager'
    tisseo_endiv.ogive.manager.object:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\ObjectManager'
    tisseo_endiv.ogive.manager.event_datasource:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\EventDatasourceManager'
    tisseo_endiv.ogive.manager.datasource:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\DatasourceManager'
    tisseo_endiv.ogive.manager.board:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: 'Tisseo\EndivBundle\Services\Ogive\BoardManager'
