parameters:
    tisseo_endiv.ogive.manager.ogive.class: Tisseo\EndivBundle\Services\Ogive\OgiveManager
    tisseo_endiv.ogive.manager.scenario_step.class: Tisseo\EndivBundle\Services\Ogive\ScenarioStepManager
    tisseo_endiv.ogive.manager.scenario.class: Tisseo\EndivBundle\Services\Ogive\ScenarioManager

services:
    tisseo_endiv.ogive.manager.ogive:
        abstract: true
        class: '%tisseo_endiv.ogive.manager.ogive.class%'
        arguments: ['@doctrine.orm.endiv_entity_manager']
    tisseo_endiv.ogive.manager.scenario_step:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: '%tisseo_endiv.ogive.manager.scenario_step.class%'
        calls:
            - [setSerializer, ['@jms_serializer']]
    tisseo_endiv.ogive.manager.scenario:
        parent: 'tisseo_endiv.ogive.manager.ogive'
        class: '%tisseo_endiv.ogive.manager.scenario.class%'
