services:
    tisseo_endiv.log_subscriber:
        class: 'Tisseo\EndivBundle\Listener\LogSubscriber'
        arguments: ["@security.token_storage", "@request_stack", "@jms_serializer"]
        tags:
            - { name: doctrine.event_subscriber, connection: 'endiv' }

    tisseo_endiv.manager.abstract:
        abstract: true
        class: 'Tisseo\EndivBundle\Services\AbstractManager'
        arguments: ['@doctrine']

    tisseo_endiv.manager.accessibility_mode:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\AccessibilityModeManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\AccessibilityMode']]

    tisseo_endiv.agency_manager:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\AgencyManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Agency']]

    tisseo_endiv.calendar_manager:
        class: 'Tisseo\EndivBundle\Services\CalendarManager'
        arguments: ['@doctrine.orm.endiv_entity_manager', '@tisseo_endiv.calendar_element_manager']

    tisseo_endiv.calendar_element_manager:
        class: 'Tisseo\EndivBundle\Services\CalendarElementManager'
        arguments: ['@doctrine.orm.endiv_entity_manager', '@jms_serializer']

    tisseo_endiv.color_manager:
        class: 'Tisseo\EndivBundle\Services\ColorManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.datasource_manager:
        class: 'Tisseo\EndivBundle\Services\DatasourceManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.exception_type_manager:
        class: 'Tisseo\EndivBundle\Services\ExceptionTypeManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.manager.line:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\LineManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Line']]

    tisseo_endiv.line_version_manager:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\LineVersionManager'
        arguments: ['@tisseo_endiv.calendar_manager']
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\LineVersion']]

    tisseo_endiv.log_manager:
        class: 'Tisseo\EndivBundle\Services\LogManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.physical_mode_manager:
        class: 'Tisseo\EndivBundle\Services\PhysicalModeManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.poi_type_manager:
        class: 'Tisseo\EndivBundle\Services\PoiTypeManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.non_concurrency_manager:
        class: 'Tisseo\EndivBundle\Services\NonConcurrencyManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.property_manager:
        class: 'Tisseo\EndivBundle\Services\PropertyManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.grid_calendar_manager:
        class: 'Tisseo\EndivBundle\Services\GridCalendarManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.printing_manager:
        class: 'Tisseo\EndivBundle\Services\PrintingManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.exception_type_manager:
        class: 'Tisseo\EndivBundle\Services\ExceptionTypeManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.route_manager:
        class: 'Tisseo\EndivBundle\Services\RouteManager'
        arguments: ['@doctrine.orm.endiv_entity_manager', '@tisseo_endiv.stop_manager']

    tisseo_endiv.stored_procedure_manager:
        class: 'Tisseo\EndivBundle\Services\StoredProcedureManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.stop_manager:
        class: 'Tisseo\EndivBundle\Services\StopManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.stop_area_manager:
        class: 'Tisseo\EndivBundle\Services\StopAreaManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.trip_manager:
        class: 'Tisseo\EndivBundle\Services\TripManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.odt_area_manager:
        class: 'Tisseo\EndivBundle\Services\OdtAreaManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.odt_stop_manager:
        class: 'Tisseo\EndivBundle\Services\OdtStopManager'
        arguments: ['@doctrine.orm.endiv_entity_manager', '@tisseo_endiv.stop_manager', '@tisseo_endiv.stop_area_manager']

    tisseo_endiv.city_manager:
        class: 'Tisseo\EndivBundle\Services\CityManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.schematic_manager:
        class: 'Tisseo\EndivBundle\Services\SchematicManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.transfer_manager:
        class: 'Tisseo\EndivBundle\Services\TransferManager'
        arguments: ['@doctrine.orm.endiv_entity_manager', '@tisseo_endiv.stop_manager', '@tisseo_endiv.stop_area_manager']

    tisseo_endiv.routestop_manager:
        class: 'Tisseo\EndivBundle\Services\RouteStopManager'
        arguments: ['@doctrine.orm.endiv_entity_manager', '@jms_serializer']

    tisseo_endiv.stoptime_manager:
        class: 'Tisseo\EndivBundle\Services\StopTimeManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.line_group_gis_manager:
        class: 'Tisseo\EndivBundle\Services\LineGroupGisManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.line_group_gis_content_manager:
        class: 'Tisseo\EndivBundle\Services\LineGroupGisContentManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.printing_line_group_gis_manager:
        class: 'Tisseo\EndivBundle\Services\PrintingLineGroupGisManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.line_group_manager:
        class: 'Tisseo\EndivBundle\Services\LineGroupManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.line_group_content_manager:
        class: 'Tisseo\EndivBundle\Services\LineGroupContentManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.modification_manager:
        class: 'Tisseo\EndivBundle\Services\ModificationManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.depot_manager:
        class: 'Tisseo\EndivBundle\Services\DepotManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']
    tisseo_endiv.line_status_manager:
        class: 'Tisseo\EndivBundle\Services\LineStatusManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']
