services:
    tisseo_endiv.log_subscriber:
        class: 'Tisseo\EndivBundle\Listener\LogSubscriber'
        arguments: ["@security.token_storage", "@request_stack", "@jms_serializer"]
        tags:
            - { name: doctrine.event_subscriber, connection: 'endiv' }

    tisseo_endiv.manager.abstract:
        abstract: true
        class: 'Tisseo\EndivBundle\Services\AbstractManager'
        arguments: ['@doctrine']

    tisseo_endiv.manager.accessibility_mode:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\AccessibilityModeManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\AccessibilityMode']]

    tisseo_endiv.manager.agency:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\AgencyManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Agency']]

    tisseo_endiv.manager.calendar:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\CalendarManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Calendar']]

    tisseo_endiv.manager.calendar_element:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\CalendarElementManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\CalendarElement']]

    tisseo_endiv.manager.city:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\CityManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\City']]

    tisseo_endiv.manager.color:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\ColorManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Color']]

    tisseo_endiv.manager.datasource:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\DatasourceManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Datasource']]

    tisseo_endiv.manager.exception_type:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\ExceptionTypeManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\ExceptionType']]

    tisseo_endiv.manager.grid_calendar:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\GridCalendarManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\GridCalendar']]

    tisseo_endiv.manager.line:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\LineManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Line']]

    tisseo_endiv.manager.line_group:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\LineGroupManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\LineGroup']]

    tisseo_endiv.manager.line_group_content:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\LineGroupContentManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\LineGroupContent']]

    tisseo_endiv.manager.line_group_gis:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\LineGroupGisManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\LineGroupGis']]

    tisseo_endiv.manager.line_group_gis_content:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\LineGroupGisContentManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\LineGroupGisContent']]

    tisseo_endiv.manager.line_status:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\LineStatusManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\LineStatusManager']]

    tisseo_endiv.manager.line_version:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\LineVersionManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\LineVersion']]
            - [addService, ['calendar', '@tisseo_endiv.manager.calendar']]

    tisseo_endiv.manager.log:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\LogManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Log']]

    tisseo_endiv.manager.non_concurrency:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\NonConcurrencyManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\NonConcurrency']]

    tisseo_endiv.manager.odt_area:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\OdtAreaManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\OdtArea']]

    tisseo_endiv.manager.odt_stop:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\OdtStopManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\OdtStop']]
            - [addService, ['stop', '@tisseo_endiv.manager.stop']]
            - [addService, ['stop_area', '@tisseo_endiv.manager.stop_area']]

    tisseo_endiv.manager.physical_mode:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\PhysicalModeManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\PhysicalMode']]

    tisseo_endiv.manager.poi_type:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\PoiTypeManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\PoiType']]

    tisseo_endiv.manager.printing:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\PrintingManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Printing']]

    tisseo_endiv.manager.printing_line_group_gis:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\PrintingLineGroupGisManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\PrintingLineGroupGis']]

    tisseo_endiv.manager.property:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\PropertyManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Property']]

    tisseo_endiv.manager.route:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\RouteManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Route']]
            - [addService, ['stop', '@tisseo_endiv.manager.stop']]

    tisseo_endiv.manager.route_stop:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\RouteStopManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Route']]
            - [setSerializer, ['@jms_serializer']]

    tisseo_endiv.manager.schematic:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\SchematicManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Schematic']]

    tisseo_endiv.manager.stop:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\StopManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Stop']]

    tisseo_endiv.manager.stop_area:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\StopAreaManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\StopArea']]

    tisseo_endiv.manager.stop_time:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\StopTimeManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\StopTime']]

    tisseo_endiv.manager.stored_procedure:
        class: 'Tisseo\EndivBundle\Services\StoredProcedureManager'
        arguments: ['@doctrine.orm.endiv_entity_manager']

    tisseo_endiv.manager.transfer:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\TransferManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Transfer']]
            - [addService, ['stop', '@tisseo_endiv.manager.stop']]
            - [addService, ['stop_area', '@tisseo_endiv.manager.stop_area']]

    tisseo_endiv.manager.trip:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\TripManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Trip']]

    tisseo_endiv.manager.modification:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\ModificationManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Modification']]

    tisseo_endiv.manager.depot:
        parent: 'tisseo_endiv.manager.abstract'
        class: 'Tisseo\EndivBundle\Services\DepotManager'
        calls:
            - [setClass, ['Tisseo\EndivBundle\Entity\Depot']]
