<?php

namespace Tisseo\EndivBundle\Entity\Ogive;

use Doctrine\ORM\EntityRepository;

/**
 * ConnectorParamListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectorParamListRepository extends EntityRepository
{
}
