<?php

namespace Tisseo\EndivBundle\Entity\Ogive;

use Doctrine\ORM\EntityRepository;

/**
 * DatasourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatasourceRepository extends EntityRepository
{
}
